#!/bin/sh

echo "unbound: stopping ..."
pkill unbound
sleep 3

echo "unbound: redeploy from persistent /etc/unbound to /var/unboud ..."
rm -rf /tmp/var/unbound
cp -R /etc/unbound /tmp/var/unbound
chown -R _unbound:_unbound /tmp/var/unbound/db

echo "unbound: restarting ..."
/usr/sbin/unbound

echo "unbound: running."
