#!/bin/sh

echo "nsd: stopping ..."
pkill nsd
sleep 3

echo "unbound: stopping ..."
pkill unbound
sleep 3

echo "nsd: redeploy from persistent /etc/nsd to /var/nsd ..."
for view in internal external; do
	rm -rf /tmp/var/nsd-$view
	cp -R /etc/nsd-$view /tmp/var/nsd-$view
	chown -R root:_nsd /tmp/var/nsd-$view/{db,etc,run}
	chmod 0770 /tmp/var/nsd-$view/{db,run,run/xfr}
done

echo "nsd: restarting ..."
/usr/sbin/nsd -c /var/nsd-internal/etc/nsd.conf
/usr/sbin/nsd -c /var/nsd-external/etc/nsd.conf

echo "unbound: redeploy from persistent /etc/unbound to /var/unboud ..."
rm -rf /tmp/var/unbound
cp -R /etc/unbound /tmp/var/unbound
chown -R _unbound:_unbound /tmp/var/unbound/db

echo "unbound: restarting ..."
/usr/sbin/unbound

echo "unbound: running."
